on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # # Install dependencies (if needed)
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt # Assuming your project has a requirements.txt file

      # Run your Python script to generate site/index.html
      - name: Run script to generate index.html
        run: python docs/scripts/test.py

      # Publish to Cloudflare Pages
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mkdocs-test # e.g. 'my-project'
          directory: site # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
